### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by anewuser**
.

### CODE REVIEW

**Review by RobLoach — APPROVED** [review]
Mind limiting the width of the images to 512px? If it goes greater than 512px in height, that's okay. It's just the 512px wide that's important.

THANKS!

**Review by RobLoach — CHANGES_REQUESTED** [review]
512px wide across all images :wink:

**Comment by anewuser** [comment]
I've replaced them with unfiltered raw screenshots.

**Comment by RobLoach** [comment]
This is great, thanks a lot for the updates :+1:

**Pull request merged**
